### PR TITLE
Sha256 hash with spans

### PR DESCRIPTION
**Pull request by JR-Morgan**
Major changes:
- Added new overload of the sha256 hash function.
- Changed both sha256 hash functions to use a UTF16 encoding, rather than the existing UTF8

Both the sha256 overloads behave the same given the same payload to hash.
But due to the UTF8 -> 16 change, they will result in a different hash.

There is some extra minor gotchas with this new span based overload also. The `length` property now must be a multiple of 2 (because there are two bytes per char). This is ok for us because we only use this function with a `length = 32`.

### CODE REVIEW

**Comment by JR-Morgan** [comment]
| Method      | Mean     | Error   | StdDev  | Gen0     | Gen1     | Gen2     | Allocated |
|------------ |---------:|--------:|--------:|---------:|---------:|---------:|----------:|
| Sha256      | 479.8 us | 2.89 us | 2.70 us | 199.7070 | 199.7070 | 199.7070 | 1001667 B |
| Sha256_Span | 425.1 us | 1.29 us | 1.20 us |        - |        - |        - |     152 B |

**Comment by JR-Morgan** [comment]
DAMN, this won't work...
Our input strings are WAY to big for stackalloc

**Comment by JR-Morgan** [comment]
I have an idea, but it would mean switching our sha256 hashing to use UTF16 rather than the current UTF8 bytes.

**Comment by JR-Morgan** [comment]
New numbers switching to UTF16

| Method      | Mean      | Error     | StdDev    | Gen0     | Gen1     | Gen2     | Allocated  |
|------------ |----------:|----------:|----------:|---------:|---------:|---------:|-----------:|
| Sha256      | 13.375 ms | 0.0981 ms | 0.0918 ms | 875.0000 | 875.0000 | 875.0000 | 20001762 B |
| Sha256_Span |  7.484 ms | 0.1171 ms | 0.1096 ms |        - |        - |        - |      155 B |

**Review by adamhathcock — APPROVED** [review]

**Pull request merged**
