### PR TITLE
Using Tasks for Deserialization

### PR DESCRIPTION
**Pull request by adamhathcock**
Still phases but can blur:
- check cache - lots of threads
- download - 4
- deserialize - lots of threads

Allocates a bit more it seems but way faster

### CODE REVIEW

**Comment by adamhathcock** [comment]
Speed is way better as I was getting too much from SQLite but need to cache 
image

**Comment by adamhathcock** [comment]
image
 way faster 
 
 I think the old one was 28 seconds?

**Review by gjedlicska — DISMISSED** [review]

**Comment by JR-Morgan** [comment]
Re-run the test (cache hits). looking 🔥

| Method      | Mean    | Error     | StdDev  | Gen0        | Gen1        | Gen2       | Allocated |
|------------ |--------:|----------:|--------:|------------:|------------:|-----------:|----------:|
| RunTest_Old | 24.31 s | 927.37 s  | 2.060 s | 619000.0000 | 274000.0000 | 6000.0000  |  10.75 GB |
| RunTest_New | 9.210 s | 475.352 s | 1.056 s | 588000.0000 | 292000.0000 | 6000.0000  |    9.9 GB |

**Comment by JR-Morgan** [comment]
Operations.Receive tests now:

Cache hits:
| Method           | Mean    | Error   | StdDev  | Gen0        | Gen1        | Gen2      | Allocated |
|----------------- |--------:|--------:|--------:|------------:|------------:|----------:|----------:|
| RunTest_Receive  | 22.08 s | 2.468 s | 0.641 s | 615000.0000 | 268000.0000 | 2000.0000 |  10.75 GB |
| RunTest_Receive2 | 14.60 s | 3.886 s | 1.009 s | 599000.0000 | 290000.0000 | 1000.0000 |  10.16 GB |

Cache miss:

todo...

**Review by JR-Morgan — APPROVED** [review]

**Comment by JR-Morgan** [comment]
We got cache misses a bit closer by tweaking some of the batch sizes. Proably more performance we can squeeze out of this, but seeing that the cache hits is so much faster, and is the most common type of receive, I say we accept.


Cache Miss (new)

| Method           | Mean    | Error | Gen0        | Gen1        | Gen2      | Allocated |
|----------------- |--------:|------:|------------:|------------:|----------:|----------:|
| RunTest_Receive  | 59.49 s |    NA | 614000.0000 | 268000.0000 | 1000.0000 |  10.75 GB |
| RunTest_Receive2 | 81.90 s |    NA | 587000.0000 | 295000.0000 | 1000.0000 |   9.94 GB |

**Pull request merged**
